### ISSUE TITLE
Theme for Aptana IDE

### ISSUE THREAD

**Issue by bueltge** [altercation/OLD-ethanschoonover.com-original#9]
https://github.com/bueltge/Aptana-Solarized

Thanks for your project; now i work still prefer in my IDE:

**Comment by Anahkiasen** [comment]
Thank you for that, was looking for an Eclipse version of Solarized. This works for Titanium too (the company that bought Aptana).

**Comment by bueltge** [comment]
sorry, i cant help you. the aptana has not an export for eclipse format.
But maybe you use this build: http://www.heresonesolution.com/2011/04/a-solarized-theme-for-aptana-in-eclipse/

**Comment by Anahkiasen** [comment]
No no it works. Aptana is based on Eclipse, Titanium too. That theme should work on all Eclipse based IDE.

**Comment by bueltge** [comment]
really; thats fine.
Its clear for me, that Aptana a add on Eclipse, but i dont find an import of the themes to eclipse.
